spring.application.name=energias-renovables
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/energias_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.docker.compose.enabled=false

# Dialecto de MySQL
# Asegurar que usa MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Configuraci�n de Hibernate (opcional)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Para que no se conecte a un contenedor de Docker
spring.datasource.hikari.maximum-pool-size=10

# spring.security.user.name=admin
# spring.security.user.password=admin123

auth0.audience=https://dev-3hlihodxgyn2r8zl.us.auth0.com/api/v2/
auth0.issuer=https://dev-3hlihodxgyn2r8zl.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.issuer-uri=${auth0.issuer}
spring.security.oauth2.resourceserver.jwt.audiences=${auth0.audience}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG